name: 'Local Cache Check and Populate'
description: 'Locally cache a custom cache directory'
inputs:
  cache_prefix:
    description: 'Prefix name for cache'
    required: true
  cache_key:
    description: 'Cache version'
    required: true
  cache_path:
    description: 'Path to be cached'
    required: true
  cache_base:
    description: 'Path to cache directory'
    required: false
    default: ${{ github.workspace }}/../../_cache
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        if [ -d "${{ inputs.cache_base }}/$cache_prefix-$cache_key/" ]; then
          rm -rf "${{ inputs.cache_base }}/$cache_prefix-$cache_key/"
        fi
        mkdir ${{ inputs.cache_base }}/$cache_prefix-$cache_key
        /usr/bin/cp -fr "$cache_path"/* "${{ inputs.cache_base }}/$cache_prefix-$cache_key" 2>/dev/null
        /usr/bin/cp -fr "$cache_path"/.* "${{ inputs.cache_base }}/$cache_prefix-$cache_key" 2>/dev/null || true
        if [ $? -ne 0 ]; then
          echo "::warning ::Caching failed"
          exit 1
        fi
      continue-on-error: true
