name: 'Local Cache Check and Populate'
description: 'Locally cache a custom cache directory'
inputs:  
  cache_prefix:
    description: 'Prefix name for cache (for stale cache deletion)'
    required: true
  cache_key:
    description: 'Cache version'
    required: true
  cache_path:
    description: 'Path to be cached'
    required: true
  cache_base:
    description: 'Path to cache directory'
    required: false
    default: ${{ github.workspace }}/../../_cache
outputs:
  cache-hit:
    description: 'True if cache key is found, false otherwise'
    value: ${{ steps.restore.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - shell: bash
      id: restore
      run: |
        if /usr/bin/find "${{ inputs.cache_base }}" -maxdepth 1 -name "$cache_prefix-$cache_key" -type d | grep -q .; then
          echo "cache-hit=true" >> $GITHUB_OUTPUT
          [ -d "$cache_path" ] || mkdir -p "$cache_path"
          cp -r "${{ inputs.cache_base }}/$cache_prefix-$cache_key"/* "${{ inputs.cache_base }}/$cache_prefix-$cache_key"/.* "$cache_path" 2>/dev/null
        else
          echo "cache-hit=false" >> $GITHUB_OUTPUT
          echo "::warning ::Cache not found. Deleting stale caches."
          if [ -d "${{ inputs.cache_base }}/$cache_prefix-$cache_key/" ]; then
            rm -rf "${{ inputs.cache_base }}/$cache_prefix-$cache_key/"
          fi
        fi
      continue-on-error: true